import type { VisualizationConfig } from "@/hooks/useCohiChat";
import type { TableColumn } from "@/types/reportTypes";
import {
  chunkRowsForPptSlides,
  PPT_TABLE_DATA_ROWS_PER_SLIDE,
  pptTablePageRowRangeLabel,
} from "@/utils/exportUtils";

export const CHAT_VIZ_PPT_PLACEHOLDER =
  "Chart preview unavailable — see data table on the next slide.";

export const CHAT_VIZ_PPT_MAX_COLUMNS = 6;
export const CHAT_VIZ_PPT_HEADER_MAX_LEN = 22;
export const CHAT_VIZ_PPT_CELL_MAX_LEN = 32;

export type ChatVizExportTablePage = {
  columns: TableColumn[];
  rows: Record<string, unknown>[];
  slideTitle: string;
  rangeLabel: string;
};

export type ChatVizExportContent = {
  title: string;
  chartTypeLabel: string;
  description?: string;
  chartImageDataUrl?: string;
  tablePages: ChatVizExportTablePage[];
};

export type BuildChatVizExportContentInput = {
  viz: VisualizationConfig;
  title?: string;
  description?: string;
  chartImageDataUrl?: string;
};

function formatChartTypeLabel(chartType: string): string {
  const label = chartType || "chart";
  return `Chart Type: ${label.charAt(0).toUpperCase()}${label.slice(1)}`;
}

function truncateCell(value: unknown): string {
  return String(value ?? "").substring(0, CHAT_VIZ_PPT_CELL_MAX_LEN);
}

function buildTableColumns(keys: string[]): TableColumn[] {
  return keys.slice(0, CHAT_VIZ_PPT_MAX_COLUMNS).map((key) => ({
    key,
    label: key.substring(0, CHAT_VIZ_PPT_HEADER_MAX_LEN),
    align: "left" as const,
  }));
}

function mapRowForExport(
  row: Record<string, unknown>,
  columns: string[],
): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const col of columns) {
    out[col] = truncateCell(row[col]);
  }
  return out;
}

/**
 * Normalized content for chat visualization PowerPoint export and Report Builder seeding.
 * Matches rules used by the chat "Download PowerPoint" action.
 */
export function buildChatVizExportContent(
  input: BuildChatVizExportContentInput,
): ChatVizExportContent {
  const { viz, description, chartImageDataUrl } = input;
  const displayTitle = input.title || viz.title || "Visualization";
  const chartType = viz.type || "chart";

  const tablePages: ChatVizExportTablePage[] = [];
  const data = viz.data || [];
  const hasTabularData =
    data.length > 0 && Object.keys(data[0] || {}).length > 0;

  if (hasTabularData) {
    const columnKeys = Object.keys(data[0]).slice(0, CHAT_VIZ_PPT_MAX_COLUMNS);
    const columns = buildTableColumns(columnKeys);
    const chunks = chunkRowsForPptSlides(data);

    chunks.forEach((chunk, pageIndex) => {
      const slideTitle =
        chunks.length > 1
          ? `${displayTitle} — Data (${pptTablePageRowRangeLabel(pageIndex, data.length)})`
          : `${displayTitle} — Data`;
      const start = pageIndex * PPT_TABLE_DATA_ROWS_PER_SLIDE + 1;
      const end = Math.min(
        (pageIndex + 1) * PPT_TABLE_DATA_ROWS_PER_SLIDE,
        data.length,
      );
      const rangeLabel = `Rows ${start}-${end} of ${data.length}`;

      tablePages.push({
        columns,
        rows: chunk.map((row) => mapRowForExport(row, columnKeys)),
        slideTitle,
        rangeLabel,
      });
    });
  }

  return {
    title: displayTitle,
    chartTypeLabel: formatChartTypeLabel(chartType),
    description: description?.trim() || undefined,
    chartImageDataUrl,
    tablePages,
  };
}

/** Footer line shared by download PPT and editor seed. */
export function chatVizPptFooterText(): string {
  return `Generated by Coheus | ${new Date().toLocaleDateString()}`;
}

export type BuildChatVizPptResult = {
  pres: {
    write: (opts: { outputType: string }) => Promise<unknown>;
    writeFile: (opts: { fileName: string }) => Promise<void>;
  };
  chartEmbedded: boolean;
};

/**
 * Build pptxgen presentation from export content (shared by file download and blob export).
 */
export async function buildChatVizPptPresentation(
  content: ChatVizExportContent,
): Promise<BuildChatVizPptResult> {
  const pptxgen = (await import("pptxgenjs")).default;
  const pres = new pptxgen();
  pres.author = "Coheus";
  pres.title = content.title;
  pres.layout = "LAYOUT_WIDE";

  const slideW = 13.333;
  const slideH = 7.5;
  const margin = 0.5;
  const contentW = slideW - margin * 2;

  const addHeader = (s: ReturnType<typeof pres.addSlide>, headerTitle: string) => {
    s.addText(headerTitle, {
      x: margin,
      y: 0.3,
      w: contentW,
      h: 0.6,
      fontSize: 24,
      bold: true,
      color: "1e293b",
      fontFace: "Arial",
    });
    s.addText(content.chartTypeLabel, {
      x: margin,
      y: 0.92,
      w: contentW,
      h: 0.3,
      fontSize: 11,
      color: "64748b",
      fontFace: "Arial",
    });
  };

  const addFooter = (s: ReturnType<typeof pres.addSlide>) => {
    s.addText(chatVizPptFooterText(), {
      x: margin,
      y: slideH - 0.4,
      w: contentW,
      h: 0.3,
      fontSize: 9,
      color: "94a3b8",
      fontFace: "Arial",
    });
  };

  const chartSlide = pres.addSlide();
  addHeader(chartSlide, content.title);

  let chartTopY = 1.4;
  if (content.description) {
    chartSlide.addText(content.description, {
      x: margin,
      y: 1.3,
      w: contentW,
      h: 0.5,
      fontSize: 12,
      color: "475569",
      fontFace: "Arial",
    });
    chartTopY = 1.9;
  }

  let chartEmbedded = false;
  if (content.chartImageDataUrl) {
    const dataUrl = content.chartImageDataUrl;
    const { width: imgW, height: imgH } = await new Promise<{
      width: number;
      height: number;
    }>((resolve) => {
      const im = new window.Image();
      im.onload = () => resolve({ width: im.width, height: im.height });
      im.onerror = () => resolve({ width: 1600, height: 900 });
      im.src = dataUrl;
    });

    const ratio = imgW / imgH || 16 / 9;
    const maxW = contentW;
    const maxH = slideH - chartTopY - 0.6;
    let drawW = maxW;
    let drawH = drawW / ratio;
    if (drawH > maxH) {
      drawH = maxH;
      drawW = drawH * ratio;
    }
    const drawX = margin + (contentW - drawW) / 2;
    const drawY = chartTopY + (maxH - drawH) / 2;

    chartSlide.addImage({
      data: dataUrl,
      x: drawX,
      y: drawY,
      w: drawW,
      h: drawH,
    });
    chartEmbedded = true;
  }

  if (!chartEmbedded) {
    chartSlide.addText(CHAT_VIZ_PPT_PLACEHOLDER, {
      x: margin,
      y: chartTopY + 1,
      w: contentW,
      h: 0.5,
      fontSize: 14,
      color: "94a3b8",
      italic: true,
      align: "center",
      fontFace: "Arial",
    });
  }

  addFooter(chartSlide);

  for (const page of content.tablePages) {
    const tableSlide = pres.addSlide();
    addHeader(tableSlide, page.slideTitle);

    const colWidth = contentW / page.columns.length;
    const headerRow = page.columns.map((col) => ({
      text: col.label,
      options: {
        bold: true,
        fill: { color: "f1f5f9" },
        color: "1e293b",
        fontFace: "Arial",
      },
    }));
    const dataRows = page.rows.map((row) =>
      page.columns.map((col) => ({
        text: String(row[col.key] ?? ""),
        options: { color: "334155", fontFace: "Arial" },
      })),
    );

    tableSlide.addTable([headerRow, ...dataRows] as any, {
      x: margin,
      y: 1.4,
      w: contentW,
      colW: page.columns.map(() => colWidth),
      border: { pt: 0.5, color: "e2e8f0" },
      fontFace: "Arial",
      fontSize: 11,
      valign: "middle",
    });

    addFooter(tableSlide);
  }

  return { pres, chartEmbedded };
}

/** Blob for in-chat preview/download without triggering browser save. */
export async function writeChatVizExportToBlob(
  content: ChatVizExportContent,
): Promise<{ blob: Blob; chartEmbedded: boolean }> {
  const { pres, chartEmbedded } = await buildChatVizPptPresentation(content);
  const output = (await pres.write({ outputType: "blob" })) as Blob;
  return { blob: output, chartEmbedded };
}

/**
 * Write a .pptx file from export content (chat Download PowerPoint).
 */
export async function writeChatVizExportToPptFile(
  content: ChatVizExportContent,
  fileName?: string,
): Promise<{ chartEmbedded: boolean }> {
  const { pres, chartEmbedded } = await buildChatVizPptPresentation(content);
  const safeName = (fileName || content.title).replace(/[^a-z0-9]/gi, "_");
  await pres.writeFile({ fileName: `${safeName}.pptx` });
  return { chartEmbedded };
}
