/**
 * LOS Field Library
 * Comprehensive library of all possible loan origination system fields
 * Allows lenders to customize field display names while preserving original source
 */

export interface LOSField {
  /** Original field name/key (used in database and API) */
  sourceKey: string;
  /** Display name (customizable by lender) */
  displayName: string;
  /** Field category */
  category: 'basic' | 'borrower' | 'property' | 'financial' | 'underwriting' | 'closing' | 'servicing' | 'metadata';
  /** Data type */
  dataType: 'string' | 'number' | 'date' | 'boolean' | 'currency' | 'percentage';
  /** Whether field is required */
  required: boolean;
  /** Description/help text */
  description?: string;
  /** Common aliases/variations of this field name */
  aliases?: string[];
  /** Encompass ICE field ID (e.g., "Fields.15", "Fields.4118") */
  encompassFieldId?: string;
}

/**
 * Comprehensive LOS Field Library
 * This is the master list of all possible loan fields
 */
export const LOS_FIELD_LIBRARY: LOSField[] = [
  // Basic Loan Information
  {
    sourceKey: 'loan_id',
    displayName: 'Loan ID',
    category: 'basic',
    dataType: 'string',
    required: true,
    description: 'Unique identifier for the loan',
    aliases: ['loan_number', 'loanNumber', 'application_id', 'applicationId', 'loanId', 'id'],
  },
  {
    sourceKey: 'loan_amount',
    displayName: 'Loan Amount',
    category: 'basic',
    dataType: 'currency',
    required: true,
    description: 'Total loan amount',
    aliases: ['amount', 'loanAmount', 'principal_amount', 'principalAmount', 'requested_amount', 'requestedAmount'],
  },
  {
    sourceKey: 'loan_type',
    displayName: 'Loan Type',
    category: 'basic',
    dataType: 'string',
    required: false,
    description: 'Type of loan (Conventional, FHA, VA, USDA, etc.)',
    aliases: ['product_type', 'productType', 'loan_product', 'loanProduct', 'product', 'loanPurpose'],
  },
  {
    sourceKey: 'status',
    displayName: 'Status',
    category: 'basic',
    dataType: 'string',
    required: false,
    description: 'Current loan status',
    aliases: ['loan_status', 'loanStatus', 'application_status', 'applicationStatus', 'state', 'stage'],
  },
  {
    sourceKey: 'application_date',
    displayName: 'Application Date',
    category: 'basic',
    dataType: 'date',
    required: false,
    description: 'Date loan application was submitted',
    aliases: ['app_date', 'appDate', 'applicationDate', 'submitted_date', 'submittedDate', 'created_date', 'createdDate'],
  },
  {
    sourceKey: 'closing_date',
    displayName: 'Closing Date',
    category: 'basic',
    dataType: 'date',
    required: false,
    description: 'Date loan was closed/funded',
    aliases: ['close_date', 'closeDate', 'closingDate', 'fund_date', 'fundDate', 'funded_date', 'fundedDate'],
  },
  {
    sourceKey: 'interest_rate',
    displayName: 'Interest Rate',
    category: 'basic',
    dataType: 'percentage',
    required: false,
    description: 'Loan interest rate',
    aliases: ['rate', 'interestRate', 'apr', 'APR', 'note_rate', 'noteRate'],
  },

  // Borrower Information
  {
    sourceKey: 'borrower_name',
    displayName: 'Borrower Name',
    category: 'borrower',
    dataType: 'string',
    required: false,
    description: 'Primary borrower full name',
    aliases: ['applicant_name', 'applicantName', 'name', 'borrowerName', 'customer_name', 'customerName'],
  },
  {
    sourceKey: 'borrower_first_name',
    displayName: 'Borrower First Name',
    category: 'borrower',
    dataType: 'string',
    required: false,
    description: 'Primary borrower first name',
    aliases: ['first_name', 'firstName', 'borrowerFirstName', 'applicant_first_name', 'applicantFirstName'],
  },
  {
    sourceKey: 'borrower_last_name',
    displayName: 'Borrower Last Name',
    category: 'borrower',
    dataType: 'string',
    required: false,
    description: 'Primary borrower last name',
    aliases: ['last_name', 'lastName', 'borrowerLastName', 'applicant_last_name', 'applicantLastName'],
  },
  {
    sourceKey: 'borrower_email',
    displayName: 'Borrower Email',
    category: 'borrower',
    dataType: 'string',
    required: false,
    description: 'Primary borrower email address',
    aliases: ['email', 'borrowerEmail', 'applicant_email', 'applicantEmail', 'customer_email', 'customerEmail'],
  },
  {
    sourceKey: 'borrower_phone',
    displayName: 'Borrower Phone',
    category: 'borrower',
    dataType: 'string',
    required: false,
    description: 'Primary borrower phone number',
    aliases: ['phone', 'borrowerPhone', 'applicant_phone', 'applicantPhone', 'customer_phone', 'customerPhone'],
  },
  {
    sourceKey: 'borrower_ssn',
    displayName: 'Borrower SSN',
    category: 'borrower',
    dataType: 'string',
    required: false,
    description: 'Primary borrower Social Security Number (anonymized in demo)',
    aliases: ['ssn', 'borrowerSSN', 'social_security_number', 'socialSecurityNumber'],
  },
  {
    sourceKey: 'borrower_dob',
    displayName: 'Borrower Date of Birth',
    category: 'borrower',
    dataType: 'date',
    required: false,
    description: 'Primary borrower date of birth',
    aliases: ['dob', 'borrowerDOB', 'date_of_birth', 'dateOfBirth', 'birth_date', 'birthDate'],
  },
  {
    sourceKey: 'co_borrower_name',
    displayName: 'Co-Borrower Name',
    category: 'borrower',
    dataType: 'string',
    required: false,
    description: 'Co-borrower full name',
    aliases: ['coborrower_name', 'coborrowerName', 'co_borrowerName', 'coBorrowerName'],
  },

  // Property Information
  {
    sourceKey: 'property_address',
    displayName: 'Property Address',
    category: 'property',
    dataType: 'string',
    required: false,
    description: 'Property street address',
    aliases: ['address', 'propertyAddress', 'subject_property_address', 'subjectPropertyAddress'],
  },
  {
    sourceKey: 'property_city',
    displayName: 'Property City',
    category: 'property',
    dataType: 'string',
    required: false,
    description: 'Property city',
    aliases: ['city', 'propertyCity', 'subject_property_city', 'subjectPropertyCity'],
  },
  {
    sourceKey: 'property_state',
    displayName: 'Property State',
    category: 'property',
    dataType: 'string',
    required: false,
    description: 'Property state',
    aliases: ['state', 'propertyState', 'subject_property_state', 'subjectPropertyState'],
  },
  {
    sourceKey: 'property_zip',
    displayName: 'Property ZIP',
    category: 'property',
    dataType: 'string',
    required: false,
    description: 'Property ZIP code',
    aliases: ['zip', 'zip_code', 'zipCode', 'propertyZip', 'subject_property_zip', 'subjectPropertyZip'],
    encompassFieldId: 'Fields.15',
  },
  {
    sourceKey: 'property_value',
    displayName: 'Property Value',
    category: 'property',
    dataType: 'currency',
    required: false,
    description: 'Appraised or estimated property value',
    aliases: ['propertyValue', 'appraised_value', 'appraisedValue', 'estimated_value', 'estimatedValue'],
  },
  {
    sourceKey: 'property_type',
    displayName: 'Property Type',
    category: 'property',
    dataType: 'string',
    required: false,
    description: 'Type of property (Single Family, Condo, etc.)',
    aliases: ['propertyType', 'subject_property_type', 'subjectPropertyType'],
  },

  // Financial Information
  {
    sourceKey: 'loan_purpose',
    displayName: 'Loan Purpose',
    category: 'financial',
    dataType: 'string',
    required: false,
    description: 'Purpose of loan (Purchase, Refinance, Cash-Out, etc.)',
    aliases: ['purpose', 'loanPurpose', 'transaction_type', 'transactionType'],
  },
  {
    sourceKey: 'ltv',
    displayName: 'Loan-to-Value (LTV)',
    category: 'financial',
    dataType: 'percentage',
    required: false,
    description: 'Loan-to-value ratio',
    aliases: ['loan_to_value', 'loanToValue', 'ltv_ratio', 'ltvRatio'],
  },
  {
    sourceKey: 'cltv',
    displayName: 'Combined LTV (CLTV)',
    category: 'financial',
    dataType: 'percentage',
    required: false,
    description: 'Combined loan-to-value ratio',
    aliases: ['combined_ltv', 'combinedLTV', 'cltv_ratio', 'cltvRatio'],
  },
  {
    sourceKey: 'fico_score',
    displayName: 'FICO Score',
    category: 'financial',
    dataType: 'number',
    required: false,
    description: 'Borrower FICO credit score',
    aliases: ['fico', 'credit_score', 'creditScore', 'ficoScore', 'middle_fico', 'middleFICO'],
  },
  {
    sourceKey: 'debt_to_income',
    displayName: 'Debt-to-Income (DTI)',
    category: 'financial',
    dataType: 'percentage',
    required: false,
    description: 'Debt-to-income ratio',
    aliases: ['dti', 'debt_to_income_ratio', 'debtToIncomeRatio', 'dti_ratio', 'dtiRatio'],
  },
  {
    sourceKey: 'monthly_income',
    displayName: 'Monthly Income',
    category: 'financial',
    dataType: 'currency',
    required: false,
    description: 'Borrower monthly income',
    aliases: ['income', 'monthlyIncome', 'borrower_income', 'borrowerIncome'],
  },
  {
    sourceKey: 'down_payment',
    displayName: 'Down Payment',
    category: 'financial',
    dataType: 'currency',
    required: false,
    description: 'Down payment amount',
    aliases: ['downPayment', 'down_payment_amount', 'downPaymentAmount'],
  },
  {
    sourceKey: 'down_payment_percent',
    displayName: 'Down Payment %',
    category: 'financial',
    dataType: 'percentage',
    required: false,
    description: 'Down payment percentage',
    aliases: ['down_payment_pct', 'downPaymentPct', 'down_payment_percentage', 'downPaymentPercentage'],
  },

  // Underwriting Information
  {
    sourceKey: 'lock_date',
    displayName: 'Lock Date',
    category: 'underwriting',
    dataType: 'date',
    required: false,
    description: 'Date interest rate was locked',
    aliases: ['lockDate', 'rate_lock_date', 'rateLockDate', 'locked_date', 'lockedDate'],
  },
  {
    sourceKey: 'lock_expiration_date',
    displayName: 'Lock Expiration Date',
    category: 'underwriting',
    dataType: 'date',
    required: false,
    description: 'Date interest rate lock expires',
    aliases: ['lockExpirationDate', 'rate_lock_expiration', 'rateLockExpiration', 'lock_expires', 'lockExpires'],
  },
  {
    sourceKey: 'submitted_to_uw_date',
    displayName: 'Submitted to UW Date',
    category: 'underwriting',
    dataType: 'date',
    required: false,
    description: 'Date submitted to underwriting',
    aliases: ['submittedDate', 'submitted_to_underwriting', 'submittedToUnderwriting', 'uw_submission_date', 'uwSubmissionDate'],
  },
  {
    sourceKey: 'approved_date',
    displayName: 'Approved Date',
    category: 'underwriting',
    dataType: 'date',
    required: false,
    description: 'Date loan was approved',
    aliases: ['approvalDate', 'approvedDate', 'approval_date', 'underwriting_approval_date', 'underwritingApprovalDate'],
  },
  {
    sourceKey: 'ctc_date',
    displayName: 'Clear to Close Date',
    category: 'underwriting',
    dataType: 'date',
    required: false,
    description: 'Date loan was cleared to close',
    aliases: ['ctcDate', 'clear_to_close_date', 'clearToCloseDate', 'ctc', 'cleared_to_close', 'clearedToClose'],
  },
  {
    sourceKey: 'credit_pull_date',
    displayName: 'Credit Pull Date',
    category: 'underwriting',
    dataType: 'date',
    required: false,
    description: 'Date credit was pulled',
    aliases: ['creditPullDate', 'credit_pull', 'creditPull', 'credit_report_date', 'creditReportDate'],
  },
  {
    sourceKey: 'underwriter_name',
    displayName: 'Underwriter Name',
    category: 'underwriting',
    dataType: 'string',
    required: false,
    description: 'Assigned underwriter name',
    aliases: ['underwriter', 'underwriterName', 'uw_name', 'uwName', 'assigned_underwriter', 'assignedUnderwriter'],
  },

  // Closing Information
  {
    sourceKey: 'closing_agent',
    displayName: 'Closing Agent',
    category: 'closing',
    dataType: 'string',
    required: false,
    description: 'Closing agent or title company',
    aliases: ['closingAgent', 'title_company', 'titleCompany', 'settlement_agent', 'settlementAgent'],
  },
  {
    sourceKey: 'closing_location',
    displayName: 'Closing Location',
    category: 'closing',
    dataType: 'string',
    required: false,
    description: 'Location where closing occurred',
    aliases: ['closingLocation', 'settlement_location', 'settlementLocation'],
  },
  {
    sourceKey: 'funding_date',
    displayName: 'Funding Date',
    category: 'closing',
    dataType: 'date',
    required: false,
    description: 'Date loan was funded',
    aliases: ['fundDate', 'funded_date', 'fundedDate', 'disbursement_date', 'disbursementDate'],
  },
  {
    sourceKey: 'recording_date',
    displayName: 'Recording Date',
    category: 'closing',
    dataType: 'date',
    required: false,
    description: 'Date documents were recorded',
    aliases: ['recordingDate', 'recorded_date', 'recordedDate'],
  },

  // Servicing Information
  {
    sourceKey: 'servicing_released',
    displayName: 'Servicing Released',
    category: 'servicing',
    dataType: 'boolean',
    required: false,
    description: 'Whether servicing has been released',
    aliases: ['servicingReleased', 'service_released', 'serviceReleased'],
  },
  {
    sourceKey: 'servicing_transfer_date',
    displayName: 'Servicing Transfer Date',
    category: 'servicing',
    dataType: 'date',
    required: false,
    description: 'Date servicing was transferred',
    aliases: ['servicingTransferDate', 'service_transfer_date', 'serviceTransferDate'],
  },
  {
    sourceKey: 'current_servicer',
    displayName: 'Current Servicer',
    category: 'servicing',
    dataType: 'string',
    required: false,
    description: 'Current loan servicer',
    aliases: ['servicer', 'currentServicer', 'servicing_company', 'servicingCompany'],
  },

  // Metadata
  {
    sourceKey: 'loan_officer_id',
    displayName: 'Loan Officer ID',
    category: 'metadata',
    dataType: 'string',
    required: false,
    description: 'ID of assigned loan officer',
    aliases: ['lo_id', 'loId', 'loanOfficerId', 'originator_id', 'originatorId'],
  },
  {
    sourceKey: 'loan_officer_name',
    displayName: 'Loan Officer Name',
    category: 'metadata',
    dataType: 'string',
    required: false,
    description: 'Name of assigned loan officer',
    aliases: ['lo_name', 'loName', 'loanOfficerName', 'originator_name', 'originatorName'],
  },
  {
    sourceKey: 'branch',
    displayName: 'Branch',
    category: 'metadata',
    dataType: 'string',
    required: false,
    description: 'Branch or office location',
    aliases: ['branch_name', 'branchName', 'office', 'office_name', 'officeName'],
  },
  {
    sourceKey: 'channel',
    displayName: 'Channel',
    category: 'metadata',
    dataType: 'string',
    required: false,
    description: 'Origination channel (Retail, Wholesale, etc.)',
    aliases: ['origination_channel', 'originationChannel', 'channel_type', 'channelType'],
  },
  {
    sourceKey: 'cycle_time_days',
    displayName: 'Cycle Time (Days)',
    category: 'metadata',
    dataType: 'number',
    required: false,
    description: 'Total days from application to funding',
    aliases: ['cycleTime', 'cycle_time', 'days_to_fund', 'daysToFund', 'processing_days', 'processingDays'],
  },
  
  // Additional Encompass ICE Fields - Comprehensive lending field library
  // Property & Address Fields
  {
    sourceKey: 'property_street_address',
    displayName: 'Property Street Address',
    category: 'property',
    dataType: 'string',
    required: false,
    description: 'Property street address',
    aliases: ['street_address', 'streetAddress', 'subject_property_street'],
    encompassFieldId: 'Fields.14',
  },
  {
    sourceKey: 'property_unit_number',
    displayName: 'Property Unit Number',
    category: 'property',
    dataType: 'string',
    required: false,
    description: 'Property unit or apartment number',
    aliases: ['unit_number', 'unitNumber', 'apartment_number'],
    encompassFieldId: 'Fields.16',
  },
  {
    sourceKey: 'property_county',
    displayName: 'Property County',
    category: 'property',
    dataType: 'string',
    required: false,
    description: 'Property county',
    aliases: ['county', 'propertyCounty'],
    encompassFieldId: 'Fields.17',
  },
  
  // Borrower Employment Fields
  {
    sourceKey: 'borrower_employer',
    displayName: 'Borrower Employer',
    category: 'borrower',
    dataType: 'string',
    required: false,
    description: 'Primary borrower employer name',
    aliases: ['employer', 'borrowerEmployer', 'employer_name', 'employerName'],
    encompassFieldId: 'Fields.FE0102',
  },
  {
    sourceKey: 'borrower_position',
    displayName: 'Borrower Position',
    category: 'borrower',
    dataType: 'string',
    required: false,
    description: 'Primary borrower job position/title',
    aliases: ['position', 'borrowerPosition', 'job_title', 'jobTitle'],
    encompassFieldId: 'Fields.FE0110',
  },
  {
    sourceKey: 'borrower_years_on_job',
    displayName: 'Borrower Years on Job',
    category: 'borrower',
    dataType: 'number',
    required: false,
    description: 'Years at current employment',
    aliases: ['years_on_job', 'yearsOnJob', 'employment_years', 'employmentYears'],
    encompassFieldId: 'Fields.FE0113',
  },
  {
    sourceKey: 'borrower_years_on_job_2nd',
    displayName: 'Borrower Years on Job - 2nd',
    category: 'borrower',
    dataType: 'number',
    required: false,
    description: 'Years at second employment',
    aliases: ['years_on_job_2nd', 'yearsOnJob2nd'],
    encompassFieldId: 'Fields.FE0113#2',
  },
  
  // Financial & Underwriting Fields
  {
    sourceKey: 'msr_value',
    displayName: 'MSR Value',
    category: 'financial',
    dataType: 'currency',
    required: false,
    description: 'Mortgage Servicing Rights value',
    aliases: ['msrValue', 'mortgage_servicing_rights', 'mortgageServicingRights'],
    encompassFieldId: 'Fields.4118',
  },
  {
    sourceKey: 'cd_applied_cure',
    displayName: 'CD Applied Cure',
    category: 'closing',
    dataType: 'currency',
    required: false,
    description: 'Closing Disclosure applied cure amount',
    aliases: ['cdAppliedCure', 'cd_cure', 'cdCure'],
    encompassFieldId: 'Fields.CD2.X2',
  },
  {
    sourceKey: 'cd_lender_credits',
    displayName: 'CD Lender Credits',
    category: 'closing',
    dataType: 'currency',
    required: false,
    description: 'Closing Disclosure lender credits',
    aliases: ['cdLenderCredits', 'lender_credits', 'lenderCredits'],
    encompassFieldId: 'Fields.CD2.XSTLC',
  },
  {
    sourceKey: 'appraisal_received_date',
    displayName: 'Appraisal Received Date',
    category: 'underwriting',
    dataType: 'date',
    required: false,
    description: 'Date appraisal was received',
    aliases: ['appraisalReceivedDate', 'appraisal_date', 'appraisalDate'],
    encompassFieldId: 'Fields.Document.DateReceived.Appraisal',
  },
  {
    sourceKey: 'du_lp_case_id',
    displayName: 'DU/LP Case ID',
    category: 'underwriting',
    dataType: 'string',
    required: false,
    description: 'Desktop Underwriter/Loan Prospector case ID',
    aliases: ['duLpCaseId', 'du_case_id', 'duCaseId', 'lp_case_id', 'lpCaseId'],
    encompassFieldId: 'Fields.DU.LP.ID',
  },
  
  // Additional common Encompass fields
  {
    sourceKey: 'loan_number',
    displayName: 'Loan Number',
    category: 'basic',
    dataType: 'string',
    required: false,
    description: 'Encompass loan number',
    aliases: ['encompass_loan_number', 'encompassLoanNumber'],
    encompassFieldId: 'Fields.1',
  },
  {
    sourceKey: 'borrower_middle_name',
    displayName: 'Borrower Middle Name',
    category: 'borrower',
    dataType: 'string',
    required: false,
    description: 'Primary borrower middle name',
    aliases: ['middle_name', 'middleName', 'borrowerMiddleName'],
    encompassFieldId: 'Fields.400',
  },
  {
    sourceKey: 'co_borrower_first_name',
    displayName: 'Co-Borrower First Name',
    category: 'borrower',
    dataType: 'string',
    required: false,
    description: 'Co-borrower first name',
    aliases: ['coBorrowerFirstName', 'coborrower_first_name'],
    encompassFieldId: 'Fields.1100',
  },
  {
    sourceKey: 'co_borrower_last_name',
    displayName: 'Co-Borrower Last Name',
    category: 'borrower',
    dataType: 'string',
    required: false,
    description: 'Co-borrower last name',
    aliases: ['coBorrowerLastName', 'coborrower_last_name'],
    encompassFieldId: 'Fields.1101',
  },
  {
    sourceKey: 'property_sales_price',
    displayName: 'Property Sales Price',
    category: 'property',
    dataType: 'currency',
    required: false,
    description: 'Property sales price',
    aliases: ['sales_price', 'salesPrice', 'purchase_price', 'purchasePrice'],
    encompassFieldId: 'Fields.2',
  },
  {
    sourceKey: 'property_appraised_value',
    displayName: 'Property Appraised Value',
    category: 'property',
    dataType: 'currency',
    required: false,
    description: 'Appraised property value',
    aliases: ['appraised_value', 'appraisedValue', 'appraisal_value', 'appraisalValue'],
    encompassFieldId: 'Fields.3',
  },
  {
    sourceKey: 'loan_term_months',
    displayName: 'Loan Term (Months)',
    category: 'basic',
    dataType: 'number',
    required: false,
    description: 'Loan term in months',
    aliases: ['loan_term', 'loanTerm', 'term', 'term_months', 'termMonths'],
    encompassFieldId: 'Fields.4',
  },
  {
    sourceKey: 'amortization_type',
    displayName: 'Amortization Type',
    category: 'basic',
    dataType: 'string',
    required: false,
    description: 'Loan amortization type',
    aliases: ['amortizationType', 'amort_type', 'amortType'],
    encompassFieldId: 'Fields.5',
  },
  {
    sourceKey: 'occupancy_type',
    displayName: 'Occupancy Type',
    category: 'property',
    dataType: 'string',
    required: false,
    description: 'Property occupancy type (Primary, Secondary, Investment)',
    aliases: ['occupancyType', 'occupancy', 'occupancy_status', 'occupancyStatus'],
    encompassFieldId: 'Fields.19',
  },
  {
    sourceKey: 'property_usage_type',
    displayName: 'Property Usage Type',
    category: 'property',
    dataType: 'string',
    required: false,
    description: 'Property usage type',
    aliases: ['propertyUsageType', 'usage_type', 'usageType'],
    encompassFieldId: 'Fields.20',
  },
  {
    sourceKey: 'lock_period_days',
    displayName: 'Lock Period (Days)',
    category: 'underwriting',
    dataType: 'number',
    required: false,
    description: 'Interest rate lock period in days',
    aliases: ['lockPeriod', 'lock_period', 'rate_lock_period', 'rateLockPeriod'],
    encompassFieldId: 'Fields.334',
  },
  {
    sourceKey: 'lock_type',
    displayName: 'Lock Type',
    category: 'underwriting',
    dataType: 'string',
    required: false,
    description: 'Rate lock type (Float, Locked, etc.)',
    aliases: ['lockType', 'rate_lock_type', 'rateLockType'],
    encompassFieldId: 'Fields.335',
  },
  {
    sourceKey: 'total_assets',
    displayName: 'Total Assets',
    category: 'financial',
    dataType: 'currency',
    required: false,
    description: 'Borrower total assets',
    aliases: ['totalAssets', 'assets', 'total_asset_value', 'totalAssetValue'],
    encompassFieldId: 'Fields.1000',
  },
  {
    sourceKey: 'total_liabilities',
    displayName: 'Total Liabilities',
    category: 'financial',
    dataType: 'currency',
    required: false,
    description: 'Borrower total liabilities',
    aliases: ['totalLiabilities', 'liabilities', 'total_liability_value', 'totalLiabilityValue'],
    encompassFieldId: 'Fields.1001',
  },
  {
    sourceKey: 'reserves',
    displayName: 'Reserves',
    category: 'financial',
    dataType: 'currency',
    required: false,
    description: 'Borrower reserves',
    aliases: ['reserve_amount', 'reserveAmount', 'cash_reserves', 'cashReserves'],
    encompassFieldId: 'Fields.1002',
  },
  {
    sourceKey: 'gift_funds',
    displayName: 'Gift Funds',
    category: 'financial',
    dataType: 'currency',
    required: false,
    description: 'Gift funds amount',
    aliases: ['giftFunds', 'gift_fund_amount', 'giftFundAmount'],
    encompassFieldId: 'Fields.1003',
  },
  {
    sourceKey: 'seller_credits',
    displayName: 'Seller Credits',
    category: 'financial',
    dataType: 'currency',
    required: false,
    description: 'Seller credit amount',
    aliases: ['sellerCredits', 'seller_credit', 'sellerCredit'],
    encompassFieldId: 'Fields.1004',
  },
  {
    sourceKey: 'loan_to_cost',
    displayName: 'Loan to Cost (LTC)',
    category: 'financial',
    dataType: 'percentage',
    required: false,
    description: 'Loan-to-cost ratio',
    aliases: ['ltc', 'loan_to_cost_ratio', 'loanToCostRatio'],
    encompassFieldId: 'Fields.1005',
  },
  {
    sourceKey: 'combined_ltv_cltv',
    displayName: 'Combined LTV (CLTV)',
    category: 'financial',
    dataType: 'percentage',
    required: false,
    description: 'Combined loan-to-value including second liens',
    aliases: ['cltv', 'combined_ltv', 'combinedLTV'],
    encompassFieldId: 'Fields.1006',
  },
  {
    sourceKey: 'housing_ratio',
    displayName: 'Housing Ratio',
    category: 'financial',
    dataType: 'percentage',
    required: false,
    description: 'Front-end debt-to-income ratio (housing payment to income)',
    aliases: ['housingRatio', 'front_end_dti', 'frontEndDti', 'housing_dti', 'housingDti'],
    encompassFieldId: 'Fields.1007',
  },
  {
    sourceKey: 'total_debt_ratio',
    displayName: 'Total Debt Ratio',
    category: 'financial',
    dataType: 'percentage',
    required: false,
    description: 'Back-end debt-to-income ratio (total debt to income)',
    aliases: ['totalDebtRatio', 'back_end_dti', 'backEndDti', 'total_dti', 'totalDti'],
    encompassFieldId: 'Fields.1008',
  },
  {
    sourceKey: 'credit_score_equifax',
    displayName: 'Equifax Credit Score',
    category: 'financial',
    dataType: 'number',
    required: false,
    description: 'Equifax credit score',
    aliases: ['equifax_score', 'equifaxScore', 'eq_score', 'eqScore'],
    encompassFieldId: 'Fields.1009',
  },
  {
    sourceKey: 'credit_score_experian',
    displayName: 'Experian Credit Score',
    category: 'financial',
    dataType: 'number',
    required: false,
    description: 'Experian credit score',
    aliases: ['experian_score', 'experianScore', 'exp_score', 'expScore'],
    encompassFieldId: 'Fields.1010',
  },
  {
    sourceKey: 'credit_score_transunion',
    displayName: 'TransUnion Credit Score',
    category: 'financial',
    dataType: 'number',
    required: false,
    description: 'TransUnion credit score',
    aliases: ['transunion_score', 'transunionScore', 'tu_score', 'tuScore'],
    encompassFieldId: 'Fields.1011',
  },
  {
    sourceKey: 'middle_fico_score',
    displayName: 'Middle FICO Score',
    category: 'financial',
    dataType: 'number',
    required: false,
    description: 'Middle of three credit scores',
    aliases: ['middleFico', 'middle_fico', 'mid_fico', 'midFico'],
    encompassFieldId: 'Fields.1012',
  },
  {
    sourceKey: 'loan_program',
    displayName: 'Loan Program',
    category: 'basic',
    dataType: 'string',
    required: false,
    description: 'Loan program name',
    aliases: ['program', 'loanProgram', 'product_name', 'productName'],
    encompassFieldId: 'Fields.1013',
  },
  {
    sourceKey: 'loan_purpose_detail',
    displayName: 'Loan Purpose Detail',
    category: 'financial',
    dataType: 'string',
    required: false,
    description: 'Detailed loan purpose',
    aliases: ['loanPurposeDetail', 'purpose_detail', 'purposeDetail'],
    encompassFieldId: 'Fields.1014',
  },
  {
    sourceKey: 'refinance_cash_out_amount',
    displayName: 'Refinance Cash Out Amount',
    category: 'financial',
    dataType: 'currency',
    required: false,
    description: 'Cash-out refinance amount',
    aliases: ['cashOutAmount', 'cash_out', 'cashOut', 'refi_cash_out', 'refiCashOut'],
    encompassFieldId: 'Fields.1015',
  },
  {
    sourceKey: 'mi_required',
    displayName: 'MI Required',
    category: 'financial',
    dataType: 'boolean',
    required: false,
    description: 'Whether mortgage insurance is required',
    aliases: ['miRequired', 'mortgage_insurance_required', 'mortgageInsuranceRequired', 'pmi_required', 'pmiRequired'],
    encompassFieldId: 'Fields.1016',
  },
  {
    sourceKey: 'mi_rate',
    displayName: 'MI Rate',
    category: 'financial',
    dataType: 'percentage',
    required: false,
    description: 'Mortgage insurance rate',
    aliases: ['miRate', 'mortgage_insurance_rate', 'mortgageInsuranceRate', 'pmi_rate', 'pmiRate'],
    encompassFieldId: 'Fields.1017',
  },
  {
    sourceKey: 'mi_company',
    displayName: 'MI Company',
    category: 'financial',
    dataType: 'string',
    required: false,
    description: 'Mortgage insurance company',
    aliases: ['miCompany', 'mortgage_insurance_company', 'mortgageInsuranceCompany', 'pmi_company', 'pmiCompany'],
    encompassFieldId: 'Fields.1018',
  },
  {
    sourceKey: 'title_company',
    displayName: 'Title Company',
    category: 'closing',
    dataType: 'string',
    required: false,
    description: 'Title company name',
    aliases: ['titleCompany', 'title_insurance_company', 'titleInsuranceCompany'],
    encompassFieldId: 'Fields.1019',
  },
  {
    sourceKey: 'escrow_company',
    displayName: 'Escrow Company',
    category: 'closing',
    dataType: 'string',
    required: false,
    description: 'Escrow company name',
    aliases: ['escrowCompany', 'settlement_company', 'settlementCompany'],
    encompassFieldId: 'Fields.1020',
  },
  {
    sourceKey: 'appraisal_company',
    displayName: 'Appraisal Company',
    category: 'underwriting',
    dataType: 'string',
    required: false,
    description: 'Appraisal company name',
    aliases: ['appraisalCompany', 'appraiser_company', 'appraiserCompany'],
    encompassFieldId: 'Fields.1021',
  },
  {
    sourceKey: 'appraisal_value',
    displayName: 'Appraisal Value',
    category: 'property',
    dataType: 'currency',
    required: false,
    description: 'Appraised property value',
    aliases: ['appraisalValue', 'appraised_value', 'appraisedValue'],
    encompassFieldId: 'Fields.1022',
  },
  {
    sourceKey: 'appraisal_ordered_date',
    displayName: 'Appraisal Ordered Date',
    category: 'underwriting',
    dataType: 'date',
    required: false,
    description: 'Date appraisal was ordered',
    aliases: ['appraisalOrderedDate', 'appraisal_order_date', 'appraisalOrderDate'],
    encompassFieldId: 'Fields.1023',
  },
  {
    sourceKey: 'flood_zone',
    displayName: 'Flood Zone',
    category: 'property',
    dataType: 'string',
    required: false,
    description: 'FEMA flood zone designation',
    aliases: ['floodZone', 'fema_flood_zone', 'femaFloodZone'],
    encompassFieldId: 'Fields.1024',
  },
  {
    sourceKey: 'flood_insurance_required',
    displayName: 'Flood Insurance Required',
    category: 'property',
    dataType: 'boolean',
    required: false,
    description: 'Whether flood insurance is required',
    aliases: ['floodInsuranceRequired', 'flood_insurance_req', 'floodInsuranceReq'],
    encompassFieldId: 'Fields.1025',
  },
  {
    sourceKey: 'hazard_insurance_required',
    displayName: 'Hazard Insurance Required',
    category: 'property',
    dataType: 'boolean',
    required: false,
    description: 'Whether hazard insurance is required',
    aliases: ['hazardInsuranceRequired', 'hazard_insurance_req', 'hazardInsuranceReq', 'homeowners_insurance', 'homeownersInsurance'],
    encompassFieldId: 'Fields.1026',
  },

  // ========== QLIK-SPECIFIC FIELDS FOR COHI INTELLIGENCE ==========
  // Additional Date Fields for Qlik Date Flags and Turn Times
  {
    sourceKey: 'investor_purchase_date',
    displayName: 'Investor Purchase Date',
    category: 'closing',
    dataType: 'date',
    required: false,
    description: 'Date loan was sold to investor (Qlik: Used for pull-through calculations)',
    aliases: ['investorPurchaseDate', 'investor_purchase', 'investorPurchase', 'sold_date', 'soldDate', 'purchase_date', 'purchaseDate'],
  },
  {
    sourceKey: 'funding_date',
    displayName: 'Funding Date',
    category: 'closing',
    dataType: 'date',
    required: false,
    description: 'Date loan was funded (Qlik: Used for App-Fund turn time and funded flag)',
    aliases: ['fundDate', 'funded_date', 'fundedDate', 'disbursement_date', 'disbursementDate'],
  },
  {
    sourceKey: 'shipped_date',
    displayName: 'Shipped Date',
    category: 'closing',
    dataType: 'date',
    required: false,
    description: 'Date loan was shipped to investor',
    aliases: ['shippedDate', 'shipped', 'ship_date', 'shipDate'],
  },
  {
    sourceKey: 'funds_sent_date',
    displayName: 'Funds Sent Date',
    category: 'closing',
    dataType: 'date',
    required: false,
    description: 'Date funds were sent',
    aliases: ['fundsSentDate', 'funds_sent', 'fundsSent'],
  },
  {
    sourceKey: 'registration_date',
    displayName: 'Registration Date',
    category: 'basic',
    dataType: 'date',
    required: false,
    description: 'Date loan was registered in system',
    aliases: ['registrationDate', 'registered_date', 'registeredDate'],
    // Note: Registration Date is NOT found in the Encompass 2020 URLA Field Guide
    // This is likely a custom field or maps to another standard field (e.g., Started Date, Application Date)
    // To find the correct field ID:
    // 1. Use Encompass Field Search API: https://developer.icemortgagetechnology.com/developer-connect/reference/field-search
    // 2. Check your Encompass instance's custom fields
    // 3. Verify if it maps to "Started Date" (Fields.XXXX) or "Application Date" (Fields.15)
    // encompassFieldId: 'Fields.XXXX', // TODO: Verify actual field ID in your Encompass instance
  },
  {
    sourceKey: 'started_date',
    displayName: 'Started Date',
    category: 'basic',
    dataType: 'date',
    required: false,
    description: 'Date loan application was started',
    aliases: ['startedDate', 'start_date', 'startDate', 'loan_started_date', 'loanStartedDate'],
  },
  {
    sourceKey: 'loan_estimate_sent_date',
    displayName: 'Loan Estimate Sent Date',
    category: 'underwriting',
    dataType: 'date',
    required: false,
    description: 'Date Loan Estimate (LE) was sent to borrower',
    aliases: ['loanEstimateSentDate', 'le_sent_date', 'leSentDate', 'le_sent', 'leSent'],
  },
  {
    sourceKey: 'loan_estimate_received_date',
    displayName: 'Loan Estimate Received Date',
    category: 'underwriting',
    dataType: 'date',
    required: false,
    description: 'Date Loan Estimate (LE) was received by borrower',
    aliases: ['loanEstimateReceivedDate', 'le_received_date', 'leReceivedDate', 'le_received', 'leReceived'],
  },
  {
    sourceKey: 'closing_disclosure_sent_date',
    displayName: 'Closing Disclosure Sent Date',
    category: 'closing',
    dataType: 'date',
    required: false,
    description: 'Date Closing Disclosure (CD) was sent',
    aliases: ['closingDisclosureSentDate', 'cd_sent_date', 'cdSentDate', 'cd_sent', 'cdSent'],
  },
  {
    sourceKey: 'closing_disclosure_received_date',
    displayName: 'Closing Disclosure Received Date',
    category: 'closing',
    dataType: 'date',
    required: false,
    description: 'Date Closing Disclosure (CD) was received',
    aliases: ['closingDisclosureReceivedDate', 'cd_received_date', 'cdReceivedDate', 'cd_received', 'cdReceived'],
  },
  {
    sourceKey: 'uw_suspended_date',
    displayName: 'UW Suspended Date',
    category: 'underwriting',
    dataType: 'date',
    required: false,
    description: 'Date underwriting was suspended',
    aliases: ['uwSuspendedDate', 'underwriting_suspended_date', 'underwritingSuspendedDate', 'suspended_date', 'suspendedDate'],
  },
  {
    sourceKey: 'uw_denied_date',
    displayName: 'UW Denied Date',
    category: 'underwriting',
    dataType: 'date',
    required: false,
    description: 'Date loan was denied by underwriting',
    aliases: ['uwDeniedDate', 'underwriting_denied_date', 'underwritingDeniedDate', 'denied_date', 'deniedDate'],
  },
  {
    sourceKey: 'uw_final_approval_date',
    displayName: 'UW Final Approval Date',
    category: 'underwriting',
    dataType: 'date',
    required: false,
    description: 'Date final underwriting approval was granted',
    aliases: ['uwFinalApprovalDate', 'underwriting_final_approval_date', 'underwritingFinalApprovalDate', 'final_approval_date', 'finalApprovalDate'],
  },
  {
    sourceKey: 'submitted_to_processing_date',
    displayName: 'Submitted to Processing Date',
    category: 'underwriting',
    dataType: 'date',
    required: false,
    description: 'Date loan was submitted to processing',
    aliases: ['submittedToProcessingDate', 'submitted_to_processing', 'submittedToProcessing', 'processing_submission_date', 'processingSubmissionDate'],
  },
  {
    sourceKey: 'submitted_to_underwriting_date',
    displayName: 'Submitted to Underwriting Date',
    category: 'underwriting',
    dataType: 'date',
    required: false,
    description: 'Date loan was submitted to underwriting',
    aliases: ['submittedToUnderwritingDate', 'submitted_to_underwriting', 'submittedToUnderwriting', 'uw_submission_date', 'uwSubmissionDate'],
  },
  {
    sourceKey: 'estimated_closing_date',
    displayName: 'Estimated Closing Date',
    category: 'closing',
    dataType: 'date',
    required: false,
    description: 'Estimated closing date for forecasting',
    aliases: ['estimatedClosingDate', 'estimated_close_date', 'estimatedCloseDate', 'projected_closing_date', 'projectedClosingDate'],
  },

  // Revenue Fields (Qlik: Total Revenue = Origination + Secondary)
  {
    sourceKey: 'origination_revenue',
    displayName: 'Origination Revenue',
    category: 'financial',
    dataType: 'currency',
    required: false,
    description: 'Revenue from origination (points and fees) - Qlik: Base Buy Dollars * (Points / 100) + Fees',
    aliases: ['originationRevenue', 'orig_revenue', 'origRevenue', 'origination_income', 'originationIncome'],
  },
  {
    sourceKey: 'secondary_revenue',
    displayName: 'Secondary Revenue',
    category: 'financial',
    dataType: 'currency',
    required: false,
    description: 'Revenue from secondary market sale (gain on sale) - Qlik: Base Sell Dollars - Base Buy Dollars',
    aliases: ['secondaryRevenue', 'sec_revenue', 'secRevenue', 'secondary_income', 'secondaryIncome', 'gain_on_sale', 'gainOnSale'],
  },
  {
    sourceKey: 'total_revenue',
    displayName: 'Total Revenue',
    category: 'financial',
    dataType: 'currency',
    required: false,
    description: 'Total revenue (Origination + Secondary) - Qlik: RangeSum(Origination Revenue, Secondary Revenue)',
    aliases: ['totalRevenue', 'revenue', 'total_income', 'totalIncome'],
  },
  {
    sourceKey: 'base_buy_dollars',
    displayName: 'Base Buy Dollars',
    category: 'financial',
    dataType: 'currency',
    required: false,
    description: 'Base buy price for revenue calculations',
    aliases: ['baseBuyDollars', 'base_buy', 'baseBuy', 'buy_price', 'buyPrice'],
  },
  {
    sourceKey: 'base_sell_dollars',
    displayName: 'Base Sell Dollars',
    category: 'financial',
    dataType: 'currency',
    required: false,
    description: 'Base sell price for revenue calculations',
    aliases: ['baseSellDollars', 'base_sell', 'baseSell', 'sell_price', 'sellPrice'],
  },
  {
    sourceKey: 'points',
    displayName: 'Points',
    category: 'financial',
    dataType: 'number',
    required: false,
    description: 'Loan points (used in origination revenue calculation)',
    aliases: ['loan_points', 'loanPoints', 'discount_points', 'discountPoints'],
  },
  {
    sourceKey: 'fees',
    displayName: 'Fees',
    category: 'financial',
    dataType: 'currency',
    required: false,
    description: 'Loan fees (used in origination revenue calculation)',
    aliases: ['loan_fees', 'loanFees', 'origination_fees', 'originationFees'],
  },

  // Complexity Fields (Qlik: Used in TopTiering and Cohi)
  {
    sourceKey: 'fico_complexity',
    displayName: 'FICO Complexity',
    category: 'financial',
    dataType: 'number',
    required: false,
    description: 'Qlik: Complexity score based on FICO (< 640 = 3, < 680 = 2, < 720 = 1, else 0)',
    aliases: ['ficoComplexity', 'fico_complexity_score', 'ficoComplexityScore'],
  },
  {
    sourceKey: 'dti_complexity',
    displayName: 'DTI Complexity',
    category: 'financial',
    dataType: 'number',
    required: false,
    description: 'Qlik: Complexity score based on DTI (> 45 = 3, > 40 = 2, > 35 = 1, else 0)',
    aliases: ['dtiComplexity', 'dti_complexity_score', 'dtiComplexityScore'],
  },
  {
    sourceKey: 'ltv_complexity',
    displayName: 'LTV Complexity',
    category: 'financial',
    dataType: 'number',
    required: false,
    description: 'Qlik: Complexity score based on LTV (> 90 = 3, > 80 = 2, > 70 = 1, else 0)',
    aliases: ['ltvComplexity', 'ltv_complexity_score', 'ltvComplexityScore'],
  },
  {
    sourceKey: 'loan_complexity_score',
    displayName: 'Loan Complexity Score',
    category: 'financial',
    dataType: 'number',
    required: false,
    description: 'Qlik: Aggregated complexity score (FICO + DTI + LTV complexity)',
    aliases: ['complexity_score', 'complexityScore', 'loanComplexity', 'total_complexity', 'totalComplexity'],
  },
  {
    sourceKey: 'risk_factor',
    displayName: 'Risk Factor',
    category: 'financial',
    dataType: 'number',
    required: false,
    description: 'Qlik: Weighted risk factor (40% complexity, 30% FICO, 20% DTI, 10% LTV)',
    aliases: ['riskFactor', 'weighted_risk', 'weightedRisk'],
  },

  // Employee Fields (Qlik: Used in Leaderboard and TopTiering)
  {
    sourceKey: 'processor',
    displayName: 'Processor',
    category: 'metadata',
    dataType: 'string',
    required: false,
    description: 'Assigned processor name',
    aliases: ['processor_name', 'processorName', 'assigned_processor', 'assignedProcessor'],
  },
  {
    sourceKey: 'closer',
    displayName: 'Closer',
    category: 'metadata',
    dataType: 'string',
    required: false,
    description: 'Assigned closer name',
    aliases: ['closer_name', 'closerName', 'assigned_closer', 'assignedCloser'],
  },
  {
    sourceKey: 'account_executive',
    displayName: 'Account Executive',
    category: 'metadata',
    dataType: 'string',
    required: false,
    description: 'Account executive name',
    aliases: ['accountExecutive', 'ae', 'ae_name', 'aeName', 'sales_rep', 'salesRep'],
  },
  {
    sourceKey: 'sales_rep_ae',
    displayName: 'Sales Rep/AE',
    category: 'metadata',
    dataType: 'string',
    required: false,
    description: 'Sales representative or account executive',
    aliases: ['salesRepAe', 'sales_rep_ae', 'originator_ae', 'originatorAe'],
  },
  {
    sourceKey: 'originator_loan_officer_name',
    displayName: 'Originator Loan Officer Name',
    category: 'metadata',
    dataType: 'string',
    required: false,
    description: 'Originator or loan officer name',
    aliases: ['originatorLoanOfficerName', 'originator_lo_name', 'originatorLoName'],
  },
  {
    sourceKey: 'broker_lender_name',
    displayName: 'Broker Lender Name',
    category: 'metadata',
    dataType: 'string',
    required: false,
    description: 'Broker or lender name',
    aliases: ['brokerLenderName', 'broker_lender', 'brokerLender'],
  },

  // Channel Fields (Qlik: Used in Channel Pull-through calculations)
  {
    sourceKey: 'tpo_company_name',
    displayName: 'TPO Company Name',
    category: 'metadata',
    dataType: 'string',
    required: false,
    description: 'Third Party Originator company name',
    aliases: ['tpoCompanyName', 'tpo_company', 'tpoCompany', 'wholesale_company', 'wholesaleCompany'],
  },
  {
    sourceKey: 'warehouse_co_name',
    displayName: 'Warehouse Co Name',
    category: 'metadata',
    dataType: 'string',
    required: false,
    description: 'Warehouse company name',
    aliases: ['warehouseCoName', 'warehouse_company', 'warehouseCompany', 'warehouse_line', 'warehouseLine'],
  },
  {
    sourceKey: 'investor',
    displayName: 'Investor',
    category: 'metadata',
    dataType: 'string',
    required: false,
    description: 'Investor purchasing the loan',
    aliases: ['investor_name', 'investorName', 'purchasing_investor', 'purchasingInvestor'],
  },
  {
    sourceKey: 'channel_group',
    displayName: 'Channel Group',
    category: 'metadata',
    dataType: 'string',
    required: false,
    description: 'Channel grouping for analysis',
    aliases: ['channelGroup', 'channel_category', 'channelCategory'],
  },
  {
    sourceKey: 'retail_flag',
    displayName: 'Retail Flag',
    category: 'metadata',
    dataType: 'boolean',
    required: false,
    description: 'Flag indicating retail channel',
    aliases: ['retailFlag', 'is_retail', 'isRetail'],
  },
  {
    sourceKey: 'tpo_flag',
    displayName: 'TPO Flag',
    category: 'metadata',
    dataType: 'boolean',
    required: false,
    description: 'Flag indicating TPO channel',
    aliases: ['tpoFlag', 'is_tpo', 'isTpo', 'wholesale_flag', 'wholesaleFlag'],
  },
  {
    sourceKey: 'correspondent_channel_flag',
    displayName: 'Correspondent Channel Flag',
    category: 'metadata',
    dataType: 'boolean',
    required: false,
    description: 'Flag indicating correspondent channel',
    aliases: ['correspondentChannelFlag', 'correspondent_flag', 'correspondentFlag', 'is_correspondent', 'isCorrespondent'],
  },

  // Turn Time Fields (Qlik: Calculated fields for performance metrics)
  {
    sourceKey: 'app_fund_turn_time',
    displayName: 'App-Fund Turn Time',
    category: 'metadata',
    dataType: 'number',
    required: false,
    description: 'Qlik: Days from application to funding (DATE(funding_date) - DATE(application_date))',
    aliases: ['appFundTurnTime', 'app_to_fund', 'appToFund', 'application_to_funding', 'applicationToFunding'],
  },
  {
    sourceKey: 'app_close_turn_time',
    displayName: 'App-Close Turn Time',
    category: 'metadata',
    dataType: 'number',
    required: false,
    description: 'Qlik: Days from application to closing (DATE(closing_date) - DATE(application_date))',
    aliases: ['appCloseTurnTime', 'app_to_close', 'appToClose', 'application_to_closing', 'applicationToClosing'],
  },
  {
    sourceKey: 'app_invpurch_turn_time',
    displayName: 'App-InvPurch Turn Time',
    category: 'metadata',
    dataType: 'number',
    required: false,
    description: 'Qlik: Days from application to investor purchase',
    aliases: ['appInvpurchTurnTime', 'app_to_invpurch', 'appToInvpurch', 'application_to_investor_purchase', 'applicationToInvestorPurchase'],
  },
  {
    sourceKey: 'fund_invpurch_turn_time',
    displayName: 'Fund-InvPurch Turn Time',
    category: 'metadata',
    dataType: 'number',
    required: false,
    description: 'Qlik: Days from funding to investor purchase',
    aliases: ['fundInvpurchTurnTime', 'fund_to_invpurch', 'fundToInvpurch', 'funding_to_investor_purchase', 'fundingToInvestorPurchase'],
  },
  {
    sourceKey: 'active_aging_days',
    displayName: 'Active Aging Days',
    category: 'metadata',
    dataType: 'number',
    required: false,
    description: 'Qlik: Days from application to current date for active loans (used in forecasting)',
    aliases: ['activeAgingDays', 'aging_days', 'agingDays', 'days_active', 'daysActive'],
  },
  {
    sourceKey: 'warehouse_line_duration',
    displayName: 'Warehouse Line Duration',
    category: 'metadata',
    dataType: 'number',
    required: false,
    description: 'Qlik: Days loan was held on warehouse line (funding to investor purchase)',
    aliases: ['warehouseLineDuration', 'warehouse_duration', 'warehouseDuration', 'wh_days', 'whDays'],
  },

  // Status Flags (Qlik: Used in filtering and calculations)
  {
    sourceKey: 'funded_flag',
    displayName: 'Funded Flag',
    category: 'metadata',
    dataType: 'boolean',
    required: false,
    description: 'Qlik: Flag indicating if loan has been funded (funding_date IS NOT NULL)',
    aliases: ['fundedFlag', 'is_funded', 'isFunded'],
  },
  {
    sourceKey: 'sold_flag',
    displayName: 'Sold Flag',
    category: 'metadata',
    dataType: 'boolean',
    required: false,
    description: 'Qlik: Flag indicating if loan has been sold to investor (investor_purchase_date IS NOT NULL)',
    aliases: ['soldFlag', 'is_sold', 'isSold'],
  },
  {
    sourceKey: 'active_loan_flag',
    displayName: 'Active Loan Flag',
    category: 'metadata',
    dataType: 'boolean',
    required: false,
    description: 'Qlik: Flag indicating if loan is currently active in pipeline',
    aliases: ['activeLoanFlag', 'is_active', 'isActive', 'active_flag', 'activeFlag'],
  },
  {
    sourceKey: 'locked_flag',
    displayName: 'Locked Flag',
    category: 'metadata',
    dataType: 'boolean',
    required: false,
    description: 'Qlik: Flag indicating if interest rate has been locked',
    aliases: ['lockedFlag', 'is_locked', 'isLocked'],
  },
  {
    sourceKey: 'approved_flag',
    displayName: 'Approved Flag',
    category: 'metadata',
    dataType: 'boolean',
    required: false,
    description: 'Flag indicating if loan has been approved',
    aliases: ['approvedFlag', 'is_approved', 'isApproved'],
  },
  {
    sourceKey: 'withdrawn_flag',
    displayName: 'Withdrawn Flag',
    category: 'metadata',
    dataType: 'boolean',
    required: false,
    description: 'Flag indicating if loan was withdrawn',
    aliases: ['withdrawnFlag', 'is_withdrawn', 'isWithdrawn'],
  },
  {
    sourceKey: 'denied_flag',
    displayName: 'Denied Flag',
    category: 'metadata',
    dataType: 'boolean',
    required: false,
    description: 'Flag indicating if loan was denied',
    aliases: ['deniedFlag', 'is_denied', 'isDenied'],
  },
  {
    sourceKey: 'ctc_flag',
    displayName: 'CTC Flag',
    category: 'metadata',
    dataType: 'boolean',
    required: false,
    description: 'Flag indicating Clear to Close status',
    aliases: ['ctcFlag', 'is_ctc', 'isCtc', 'clear_to_close_flag', 'clearToCloseFlag'],
  },
  {
    sourceKey: 'le_sent_flag',
    displayName: 'LE Sent Flag',
    category: 'metadata',
    dataType: 'boolean',
    required: false,
    description: 'Flag indicating Loan Estimate was sent',
    aliases: ['leSentFlag', 'le_sent', 'leSent'],
  },
  {
    sourceKey: 'appraisal_ordered_flag',
    displayName: 'Appraisal Ordered Flag',
    category: 'metadata',
    dataType: 'boolean',
    required: false,
    description: 'Flag indicating appraisal was ordered',
    aliases: ['appraisalOrderedFlag', 'appraisal_ordered', 'appraisalOrdered'],
  },
  {
    sourceKey: 'fnma_flag',
    displayName: 'FNMA Flag',
    category: 'metadata',
    dataType: 'boolean',
    required: false,
    description: 'Flag indicating Fannie Mae loan',
    aliases: ['fnmaFlag', 'is_fnma', 'isFnma', 'fannie_mae_flag', 'fannieMaeFlag'],
  },

  // Performance Metrics (Qlik: Used in Business Overview and Forecasting)
  {
    sourceKey: 'pull_through_rate',
    displayName: 'Pull Through Rate',
    category: 'metadata',
    dataType: 'percentage',
    required: false,
    description: 'Qlik: Percentage of applications that reach investor purchase (excludes active loans)',
    aliases: ['pullThroughRate', 'pull_through', 'pullThrough', 'conversion_rate', 'conversionRate'],
  },
  {
    sourceKey: 'channel_pull_through_rate',
    displayName: 'Channel Pull Through Rate',
    category: 'metadata',
    dataType: 'percentage',
    required: false,
    description: 'Qlik: Pull-through rate filtered by channel',
    aliases: ['channelPullThroughRate', 'channel_pull_through', 'channelPullThrough'],
  },
  {
    sourceKey: 'app_fund_pull_through_rate',
    displayName: 'App-Fund Pull Through Rate',
    category: 'metadata',
    dataType: 'percentage',
    required: false,
    description: 'Qlik: Percentage of applications that reach funding',
    aliases: ['appFundPullThroughRate', 'app_fund_pull_through', 'appFundPullThrough'],
  },
  {
    sourceKey: 'approval_percent',
    displayName: 'Approval %',
    category: 'metadata',
    dataType: 'percentage',
    required: false,
    description: 'Percentage of loans approved',
    aliases: ['approvalPercent', 'approval_rate', 'approvalRate'],
  },
  {
    sourceKey: 'withdrawn_percent',
    displayName: 'Withdrawn %',
    category: 'metadata',
    dataType: 'percentage',
    required: false,
    description: 'Percentage of loans withdrawn',
    aliases: ['withdrawnPercent', 'withdrawn_rate', 'withdrawnRate'],
  },
  {
    sourceKey: 'denied_percent',
    displayName: 'Denied %',
    category: 'metadata',
    dataType: 'percentage',
    required: false,
    description: 'Percentage of loans denied',
    aliases: ['deniedPercent', 'denied_rate', 'deniedRate'],
  },

  // Additional Financial Fields
  {
    sourceKey: 'concession_dollars',
    displayName: 'Concession Dollars',
    category: 'financial',
    dataType: 'currency',
    required: false,
    description: 'Concession amount in dollars',
    aliases: ['concessionDollars', 'concession', 'seller_concession', 'sellerConcession'],
  },
  {
    sourceKey: 'concession_percent',
    displayName: 'Concession Percent',
    category: 'financial',
    dataType: 'percentage',
    required: false,
    description: 'Concession percentage',
    aliases: ['concessionPercent', 'concession_pct', 'concessionPct'],
  },

  // Additional Underwriting Fields
  {
    sourceKey: 'underwriting_aus_source',
    displayName: 'Underwriting AUS Source',
    category: 'underwriting',
    dataType: 'string',
    required: false,
    description: 'Automated Underwriting System source (DU, LP, etc.)',
    aliases: ['underwritingAusSource', 'aus_source', 'ausSource', 'au_source', 'auSource'],
  },
  {
    sourceKey: 'underwriting_risk_assess_type',
    displayName: 'Underwriting Risk Assess Type',
    category: 'underwriting',
    dataType: 'string',
    required: false,
    description: 'Risk assessment type',
    aliases: ['underwritingRiskAssessType', 'risk_assess_type', 'riskAssessType'],
  },
  {
    sourceKey: 'fannie_au_decision',
    displayName: 'Fannie AU Decision',
    category: 'underwriting',
    dataType: 'string',
    required: false,
    description: 'Fannie Mae Automated Underwriting decision',
    aliases: ['fannieAuDecision', 'fannie_au', 'fannieAu', 'du_decision', 'duDecision'],
  },
  {
    sourceKey: 'cu_risk_source',
    displayName: 'CU Risk Source',
    category: 'underwriting',
    dataType: 'string',
    required: false,
    description: 'Credit Union risk source',
    aliases: ['cuRiskSource', 'cu_risk', 'cuRisk'],
  },
];

/**
 * Get field by source key
 */
export function getFieldBySourceKey(sourceKey: string): LOSField | undefined {
  return LOS_FIELD_LIBRARY.find(field => field.sourceKey === sourceKey);
}

/**
 * Find field by alias (case-insensitive)
 */
export function findFieldByAlias(alias: string): LOSField | undefined {
  const normalizedAlias = alias.toLowerCase().trim();
  return LOS_FIELD_LIBRARY.find(field => {
    if (field.sourceKey.toLowerCase() === normalizedAlias) return true;
    if (field.displayName.toLowerCase() === normalizedAlias) return true;
    return field.aliases?.some(a => a.toLowerCase() === normalizedAlias);
  });
}

/**
 * Get all fields by category
 */
export function getFieldsByCategory(category: LOSField['category']): LOSField[] {
  return LOS_FIELD_LIBRARY.filter(field => field.category === category);
}

/**
 * Field Mapping Configuration
 * Allows lenders to customize display names while preserving source keys
 */
export interface FieldMappingConfig {
  /** Source field key (from CSV/LOS) */
  sourceField: string;
  /** Target field key (in our system) */
  targetField: string;
  /** Custom display name (optional, uses library default if not provided) */
  customDisplayName?: string;
}

/**
 * Create field mapping from CSV headers to system fields
 */
export function createFieldMapping(
  csvHeaders: string[],
  customMappings?: Record<string, string>
): Record<string, string> {
  const mapping: Record<string, string> = {};

  for (const header of csvHeaders) {
    // Check custom mappings first
    if (customMappings && customMappings[header]) {
      mapping[header] = customMappings[header];
      continue;
    }

    // Try to find matching field in library
    const field = findFieldByAlias(header);
    if (field) {
      mapping[header] = field.sourceKey;
    } else {
      // If no match found, use header as-is (will be stored in raw_data)
      mapping[header] = header;
    }
  }

  return mapping;
}

/**
 * Get display name for a field (respects custom display names)
 */
export function getFieldDisplayName(
  sourceKey: string,
  customDisplayNames?: Record<string, string>
): string {
  if (customDisplayNames && customDisplayNames[sourceKey]) {
    return customDisplayNames[sourceKey];
  }

  const field = getFieldBySourceKey(sourceKey);
  return field?.displayName || sourceKey;
}
