import { publicAssetUrl } from '@hmda/utils/publicAssetUrl.js'
import { HMDA_DEFAULT_ANCHOR_YEAR } from '@hmda/services/hmdaApi.js'

/** @type {object|null} */
let manifestCache = null

async function fetchJson(url, opts = {}) {
  const res = await fetch(url, {
    ...opts,
    headers: { Accept: 'application/json', ...(opts.headers || {}) },
  })
  if (!res.ok) throw new Error(`${url} HTTP ${res.status}`)
  return res.json()
}

/** Load static years manifest (generated by scripts/build-hmda-years-manifest.mjs). */
export async function fetchHmdaYearsManifest({ force = false } = {}) {
  if (manifestCache && !force) return manifestCache
  try {
    manifestCache = await fetchJson(publicAssetUrl('data/hmda-years-manifest.json'), { cache: 'default' })
    return manifestCache
  } catch {
    manifestCache = null
    return null
  }
}

export function yearOptionsFromManifest(manifest, fallbackYears = []) {
  const lenderYears = manifest?.lenderYears?.map(String)
  if (lenderYears?.length) return [...lenderYears].sort((a, b) => Number(b) - Number(a))
  if (fallbackYears.length) return fallbackYears.map(String)
  return [String(HMDA_DEFAULT_ANCHOR_YEAR)]
}

export function lenderYearsFromManifest(manifest) {
  return yearOptionsFromManifest(manifest)
}

/** Human-readable badge for year dropdown (e.g. partial geo fallback). */
export function yearPickerBadge(manifest, year) {
  const info = manifest?.years?.[String(year)]
  if (!info) return ''
  const parts = []
  if (info.lenders && info.geo === false && info.geoFallbackYear) {
    parts.push(`map ${info.geoFallbackYear}`)
  }
  if (info.partial && !parts.length) parts.push('partial')
  return parts.length ? ` · ${parts.join(', ')}` : ''
}

export function isLenderYearAvailable(manifest, year) {
  const info = manifest?.years?.[String(year)]
  if (info) return Boolean(info.lenders)
  return true
}

export function clearHmdaYearsManifestCache() {
  manifestCache = null
}
