/**
 * useCohiWidgetData
 *
 * Fetches data for Cohi-generated widgets by executing their SQL query
 * against the tenant database via the cohi-chat API.
 */

import { useState, useEffect, useCallback } from 'react';
import { api } from '@/lib/api';
import type { VisualizationConfig } from '@/hooks/useCohiChat';

export interface CohiWidgetDataState {
  data: any[] | null;
  loading: boolean;
  error: string | null;
  refetch: () => void;
}

// ---------------------------------------------------------------------------
// Tenant resolution helper (same pattern as useWorkbenchCohi / useCohiChat)
// ---------------------------------------------------------------------------
let _cachedTenantId: string | null | undefined = undefined;

async function resolveEffectiveTenantId(
  explicitTenantId?: string | null
): Promise<string | null> {
  if (explicitTenantId) return explicitTenantId;
  if (_cachedTenantId !== undefined) return _cachedTenantId;
  try {
    const response = await api.request<
      { tenants: { id: string }[] } | { id: string }[]
    >('/api/tenants');
    const list = Array.isArray(response)
      ? response
      : (response as any).tenants || [];
    const first = list[0];
    if (first?.id) {
      _cachedTenantId = first.id;
      return _cachedTenantId;
    }
  } catch {
    // ignore
  }
  _cachedTenantId = null;
  return null;
}

/**
 * Execute a SQL query via the Cohi chat endpoint and return the results.
 * The SQL was generated by the LLM and is executed server-side with
 * proper sandboxing (READ ONLY, row limits, etc.).
 */
export function useCohiWidgetData(
  sql: string | undefined,
  tenantId?: string | null
): CohiWidgetDataState {
  const [data, setData] = useState<any[] | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [trigger, setTrigger] = useState(0);

  const refetch = useCallback(() => setTrigger((t) => t + 1), []);

  useEffect(() => {
    if (!sql) return;

    let cancelled = false;
    setLoading(true);
    setError(null);

    (async () => {
      try {
        const effectiveTid = await resolveEffectiveTenantId(tenantId);

        // Build URL with tenant_id query parameter (required by attachTenantContext middleware)
        const endpoint = effectiveTid
          ? `/api/cohi-chat/ask?tenant_id=${encodeURIComponent(effectiveTid)}`
          : '/api/cohi-chat/ask';

        // Use the existing cohi-chat ask endpoint with a hint to execute raw SQL
        // This reuses the existing security/permissions infrastructure
        const response = await api.request<{
          message: string;
          data?: any[];
          visualization?: VisualizationConfig;
          error?: string;
        }>(endpoint, {
          method: 'POST',
          body: JSON.stringify({
            question: `Execute this SQL and return the results: ${sql}`,
            tenantId: effectiveTid,
          }),
        });

        if (cancelled) return;

        if (response.error) {
          setError(response.error);
          setData(null);
        } else {
          // Prefer visualization data if available, fallback to raw data
          setData(response.visualization?.data || response.data || []);
          setError(null);
        }
      } catch (err: any) {
        if (cancelled) return;
        setError(err.message || 'Failed to fetch data');
        setData(null);
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [sql, tenantId, trigger]);

  return { data, loading, error, refetch };
}
