/**
 * Canonical navigation targets for Cohi chat routing.
 * Keep dashboard labels/paths/keywords in one place (no route aliases in resolver logic).
 */

export interface NavigationTarget {
  id: string;
  label: string;
  group: "Insights" | "Dashboards" | "TopTiering" | "Pages" | "Help";
  kind: "route" | "section";
  path?: string;
  sectionId?: string;
  keywords: string[];
}

export const NAVIGATION_TARGETS: readonly NavigationTarget[] = [
  {
    id: "company-scorecard",
    label: "Company Scorecard",
    group: "TopTiering",
    kind: "route",
    path: "/company-scorecard",
    keywords: [
      "company scorecard",
      "portfolio scorecard",
      "portfolio conversion",
      "branch pull through",
      "pull through",
      "pullthrough",
      "conversion",
    ],
  },
  {
    id: "business-overview",
    label: "Business Overview",
    group: "Dashboards",
    kind: "route",
    path: "/business-overview",
    keywords: [
      "business overview",
      "executive snapshot",
      "kpi",
      "overview",
      "company performance",
      "pipeline kpis",
    ],
  },
  {
    id: "lock-stratification",
    label: "Lock Stratification",
    group: "TopTiering",
    kind: "route",
    path: "/lock-stratification",
    keywords: [
      "lock stratification",
      "rate lock",
      "lock stage",
      "pipeline lock",
      "lock conversion",
      "pull through by stage",
    ],
  },
  {
    id: "pipeline-analysis",
    label: "Pipeline Analysis",
    group: "TopTiering",
    kind: "route",
    path: "/pipeline-analysis",
    keywords: [
      "pipeline analysis",
      "pipeline health",
      "pipeline stages",
      "milestone",
      "active pipeline",
    ],
  },
  {
    id: "workflow-conversion",
    label: "Workflow Conversion",
    group: "TopTiering",
    kind: "route",
    path: "/workflow-conversion",
    keywords: [
      "workflow conversion",
      "conversion funnel",
      "workflow stages",
      "stage conversion",
      "funnel",
    ],
  },
  {
    id: "fallout-forecast",
    label: "Closing & Fallout Forecast",
    group: "Dashboards",
    kind: "route",
    path: "/fallout-forecast",
    keywords: [
      "fallout",
      "closing fallout",
      "withdrawn",
      "withdrawal",
      "closing risk",
      "fallout forecast",
    ],
  },
  {
    id: "sales-scorecard",
    label: "Sales Scorecard",
    group: "TopTiering",
    kind: "route",
    path: "/sales-scorecard",
    keywords: [
      "sales scorecard",
      "lo scorecard",
      "loan officer scorecard",
      "lo tier",
      "loan officer tier",
      "top tier lo",
      "top tier los",
      "top tier loan officer",
      "tts",
      "top tiering score",
      "personnel tier",
      "tier bands",
    ],
  },
  {
    id: "sales-scorecard-overview",
    label: "Sales Scorecard Overview",
    group: "TopTiering",
    kind: "route",
    path: "/sales-scorecard-overview",
    keywords: [
      "sales scorecard overview",
      "scorecard overview",
      "lo overview",
      "branch scorecard overview",
    ],
  },
  {
    id: "operations-scorecard",
    label: "Operations Scorecard",
    group: "TopTiering",
    kind: "route",
    path: "/operations-scorecard",
    keywords: [
      "operations scorecard",
      "processor scorecard",
      "underwriter scorecard",
      "ops scorecard",
      "processor tier",
      "underwriter tier",
    ],
  },
  {
    id: "top-tiering-comparison",
    label: "Top Tiering Comparison",
    group: "TopTiering",
    kind: "route",
    path: "/performance/toptiering-comparison",
    keywords: [
      "top tiering comparison",
      "top tiering",
      "revenue pareto",
      "pareto tier",
      "revenue tier",
      "tier comparison",
    ],
  },
  {
    id: "high-performers",
    label: "High Performers",
    group: "TopTiering",
    kind: "route",
    path: "/high-performers",
    keywords: [
      "high performers",
      "high performer",
      "top performers dashboard",
      "star performers",
    ],
  },
  {
    id: "leaderboard",
    label: "Leaderboard",
    group: "Dashboards",
    kind: "route",
    path: "/leaderboard",
    keywords: ["leaderboard", "rankings", "top performers by volume"],
  },
  {
    id: "production-trends",
    label: "Production Trends",
    group: "TopTiering",
    kind: "route",
    path: "/production-trends",
    keywords: ["production trends", "production trend", "volume trend", "trend"],
  },
  {
    id: "insights",
    label: "Insights hub",
    group: "Pages",
    kind: "route",
    path: "/insights",
    keywords: ["insights", "dashboards", "dashboard home", "insights hub"],
  },
  {
    id: "section:CohiInsights",
    label: "Cohi Insights",
    group: "Insights",
    kind: "section",
    sectionId: "CohiInsights",
    keywords: ["insights", "dashboard", "cohi insights"],
  },
  {
    id: "section:industryNews",
    label: "Cohi Mortgage News",
    group: "Insights",
    kind: "section",
    sectionId: "industryNews",
    keywords: ["industry news", "mortgage news", "insights", "dashboard"],
  },
  {
    id: "workbench",
    label: "Workbench",
    group: "Pages",
    kind: "route",
    path: "/workbench",
    keywords: ["workbench", "canvas", "custom dashboard", "custom report"],
  },
  {
    id: "research",
    label: "Cohi Chat (Research)",
    group: "Pages",
    kind: "route",
    path: "/insights",
    keywords: ["research", "deeper analysis", "diagnose drivers", "root cause", "research lab"],
  },
  {
    id: "help-chat-history",
    label: "Chat history and folders",
    group: "Help",
    kind: "route",
    path: "/help/cohi-chat/data-chat-page",
    keywords: [
      "chat history",
      "folders",
      "full history",
      "organize conversations",
      "move to folder",
    ],
  },
  {
    id: "help-what-you-can-ask",
    label: "What you can ask",
    group: "Help",
    kind: "route",
    path: "/help/cohi-chat/what-you-can-ask",
    keywords: ["what can i ask", "cohi help", "help"],
  },
  {
    id: "help-example-queries",
    label: "Example queries",
    group: "Help",
    kind: "route",
    path: "/help/cohi-chat/example-queries",
    keywords: ["example queries", "sample prompts", "prompt examples"],
  },
  {
    id: "help-chat-workbench",
    label: "Cohi in Workbench",
    group: "Help",
    kind: "route",
    path: "/help/cohi-chat/chat-in-workbench",
    keywords: ["chat in workbench", "workbench help"],
  },
  {
    id: "help-chat-mode",
    label: "Chat mode help",
    group: "Help",
    kind: "route",
    path: "/help/cohi-chat/chat-mode",
    keywords: ["chat mode", "general chat", "data questions", "cohi chat"],
  },
  {
    id: "help-research-mode",
    label: "Research mode help",
    group: "Help",
    kind: "route",
    path: "/help/cohi-chat/research-mode",
    keywords: ["research mode", "research lab", "deep analysis", "investigation"],
  },
  {
    id: "help-insight-builder-mode",
    label: "Insight builder help",
    group: "Help",
    kind: "route",
    path: "/help/cohi-chat/insight-builder-mode",
    keywords: [
      "insight builder",
      "custom insight",
      "my insights prompt",
      "insight prompt",
    ],
  },
] as const;

export function getNavigationTargetById(
  id: string,
): NavigationTarget | undefined {
  return NAVIGATION_TARGETS.find((t) => t.id === id);
}

