{
     "fields": [
       "Fields.696",
       "Fields.995",
       "Fields.QM.X23",
       "Fields.2313",
       "Fields.LoanTeamMember.Name.Account Executive",
       "Fields.694",
       "Fields.3142",
       "Fields.2353",
       "Fields.2352",
       "Fields.Document.DateReceived.Appraisal",
       "Fields.356",
       "Fields.Log.MS.Date.Approval",
       "Fields.Log.MS.Date.Appt Reset",
       "Fields.Log.MS.Date.Appt Set",
       "Fields.915",
       "Fields.742",
       "Fields.FE0102",
       "Fields.1659",
       "Fields.1109",
       "Fields.FE0110",
       "Fields.FE0110#2",
       "Fields.FE0115",
       "Fields.FE0115#2",
       "Fields.FE0113",
       "Fields.FE0113#2",
       "Fields.ULDD.X26",
       "Fields.ULDD.X150",
       "Fields.ORGID",
       "Fields.3375",
       "Fields.315",
       "Fields.HMDA.X58",
       "Fields.2150",
       "Fields.2149",
       "Fields.2151",
       "Fields.CD2.X2",
       "Fields.CD2.XSTLC",
       "Fields.976",
       "Fields.2305",
       "Fields.MORNET.X92",
       "Fields.2626",
       "Fields.LoanTeamMember.Name.Closer",
       "Fields.Log.MS.Date.Closer Assignment",
       "Fields.LoanTeamMember.UserID.Closer",
       "Fields.748",
       "Fields.3978",
       "Fields.3977",
       "Fields.3261",
       "Fields.FE0202",
       "Fields.FE0210",
       "Fields.FE0215",
       "Fields.FE0213",
       "Fields.ULDD.X154",
       "Fields.ULDD.X151",
       "Fields.1547",
       "Fields.3237",
       "Fields.Log.MS.Date.Completion",
       "Fields.Log.MS.Date.Cond. Approval",
       "Fields.2300",
       "Fields.3371",
       "Fields.1396",
       "Fields.Document.DateReceived.CREDIT REPORT",
       "Fields.1393",
       "Fields.Log.MS.CurrentMilestone",
       "Fields.749",
       "Fields.DU.LP.ID",
       "Fields.3337",
       "Fields.3341",
       "Fields.1959",
       "Fields.Log.MS.Date.Disclosure Prep",
       "Fields.2277",
       "Fields.Log.MS.Date.Doc Preparation",
       "Fields.Log.MS.Date.Docs Out",
       "Fields.Log.MS.Date.Docs Signing",
       "Fields.MORNET.X67",
       "Fields.763",
       "Fields.QM.X103",
       "Fields.VASUMM.X23",
       "Fields.ULDD.FNM.AutoUWDec",
       "Fields.ULDD.FNM.PropertyFormType",
       "Fields.641",
       "Fields.NEWHUD2.X1101",
       "Fields.NEWHUD2.X1107",
       "Fields.NEWHUD2.X1110",
       "Fields.NEWHUD2.X1113",
       "Fields.581",
       "Fields.NEWHUD2.X1104",
       "Fields.NEWHUD2.X1100",
       "Fields.640",
       "Fields.NEWHUD2.X1134",
       "Fields.NEWHUD2.X1140",
       "Fields.NEWHUD2.X1143",
       "Fields.NEWHUD2.X1146",
       "Fields.580",
       "Fields.NEWHUD2.X1137",
       "Fields.NEWHUD2.X1133",
       "Fields.NEWHUD.X400",
       "Fields.NEWHUD2.X1200",
       "Fields.NEWHUD2.X1206",
       "Fields.NEWHUD2.X1209",
       "Fields.NEWHUD2.X1212",
       "Fields.NEWHUD.X781",
       "Fields.NEWHUD2.X1203",
       "Fields.NEWHUD2.X1199",
       "Fields.697",
       "Fields.3054",
       "Fields.2365",
       "Fields.1699",
       "Fields.ULDD.FRE.AutoUWDec",
       "Fields.ULDD.FRE.AVMModelNameExpl",
       "Fields.ULDD.X102",
       "Fields.ULDD.X101",
       "Fields.ULDD.FRE.PropertyFormType",
       "Fields.ULDD.X149",
       "Fields.ULDD.X18",
       "Fields.Log.MS.Date.Funding",
       "Fields.MS.FUN",
       "Fields.1992",
       "Fields.3142",
       "Fields.3544",
       "Fields.3545",
       "Fields.3547",
       "Fields.3546",
       "Fields.3148",
       "Fields.GUID",
       "Fields.3889",
       "Fields.1540",
       "Fields.1889",
       "Fields.1888",
       "Fields.1890",
       "Fields.2401",
       "Fields.736",
       "Fields.3143",
       "Fields.HMDA.X109",
       "Fields.CD4.X23",
       "Fields.3",
       "Fields.VEND.X263",
       "Fields.2220",
       "Fields.2370",
       "Fields.2031",
       "Fields.353",
       "Loan.LoanLastModified",
       "Fields.3253",
       "Fields.LOID",
       "Fields.420",
       "Fields.247",
       "Fields.2",
       "Fields.3153",
       "Fields.3152",
       "Fields.682",
       "Loan.LoanFolder",
       "Fields.1612",
       "Fields.364",
       "Fields.317",
       "Fields.LoanTeamMember.UserID.Loan Officer",
       "Fields.LoanTeamMember.UserID.Loan Processor",
       "Fields.1401",
       "Fields.19",
       "Fields.2024",
       "Fields.4",
       "Fields.1172",
       "Fields.761",
       "Fields.432",
       "Fields.762",
       "Fields.ARM.IdxLkbckPrd",
       "Fields.1199",
       "Fields.1205",
       "Fields.1198",
       "Fields.1200",
       "Fields.4118",
       "Fields.689",
       "Fields.688",
       "Fields.78",
       "Fields.COMPLIANCEREVIEW.X18",
       "Fields.COMPLIANCEREVIEW.X5",
       "Fields.COMPLIANCEREVIEW.X6",
       "Fields.COMPLIANCEREVIEW.X8",
       "Fields.COMPLIANCEREVIEW.X16",
       "Fields.COMPLIANCEREVIEW.X7",
       "Fields.COMPLIANCEREVIEW.X9",
       "Fields.COMPLIANCEREVIEW.X17",
       "Fields.COMPLIANCEREVIEW.X11",
       "Fields.COMPLIANCEREVIEW.X1",
       "Fields.COMPLIANCEREVIEW.X12",
       "Fields.COMPLIANCEREVIEW.X14",
       "Fields.695",
       "Fields.QM.X62",
       "Fields.1051",
       "Fields.1201",
       "Fields.L248",
       "Fields.3238",
       "Fields.2203",
       "Fields.2274",
       "Fields.992",
       "Fields.UWC.ALLCOUNT",
       "Fields.1177",
       "Fields.1548",
       "Fields.16",
       "Fields.ORGID",
       "Fields.1811",
       "Fields.NEWHUD.X686",
       "Fields.559",
       "Fields.NEWHUD.X1151",
       "Fields.5",
       "Fields.2373",
       "Fields.2391",
       "Fields.2393",
       "Fields.2395",
       "Fields.2375",
       "Fields.2377",
       "Fields.2379",
       "Fields.2381",
       "Fields.2383",
       "Fields.2385",
       "Fields.2387",
       "Fields.2389",
       "Fields.3428",
       "Fields.3424",
       "Fields.912",
       "Fields.8",
       "Fields.Log.MS.Date.Post Closing",
       "Fields.Log.MS.Date.PreApproval",
       "Fields.3336",
       "Fields.Log.MS.Date.Processing",
       "Fields.LoanTeamMember.Name.Loan Processor",
       "Fields.608",
       "Fields.12",
       "Fields.13",
       "Fields.1066",
       "Fields.14",
       "Fields.11",
       "Fields.1553",
       "Fields.ULDD.X30",
       "Fields.ULDD.X29",
       "Fields.15",
       "Fields.Log.MS.Date.Purchased",
       "Fields.QM.X24",
       "Fields.3420",
       "Fields.2161",
       "Fields.2160",
       "Fields.3380",
       "Fields.3381",
       "Fields.3382",
       "Fields.3383",
       "Fields.3384",
       "Fields.3385",
       "Fields.3386",
       "Fields.3387",
       "Fields.3388",
       "Fields.3389",
       "Fields.3390",
       "Fields.3391",
       "Fields.3392",
       "Fields.3393",
       "Fields.3394",
       "Fields.3395",
       "Fields.3257",
       "Fields.Log.MS.Date.Ready for Docs",
       "Fields.Log.MS.Date.Reconciled",
       "Fields.1822",
       "Fields.3312",
       "Fields.Log.MS.Date.Resubmittal",
       "Fields.3980",
       "Fields.3979",
       "Fields.3155",
       "Fields.3154",
       "Fields.1700",
       "Fields.2276",
       "Fields.QM.X25",
       "Fields.136",
       "Fields.Log.MS.Date.Scrubbed",
       "Fields.2221",
       "Fields.2222",
       "Fields.3888",
       "Fields.2014",
       "Fields.Log.MS.Date.Shipping",
       "Fields.Log.MS.Date.Signed",
       "Fields.Log.MS.Date.Started",
       "Fields.Log.MS.Date.Started",
       "Fields.1395",
       "Fields.Log.MS.Date.Submittal",
       "Fields.Log.MS.Date.Send To Processing",
       "Fields.Log.MS.Date.Submittal",
       "Fields.3152",
       "Fields.ULDD.TotalMortgagedPropertiesCount",
       "Fields.2987",
       "Fields.2301",
       "Fields.2303",
       "Fields.CX.Count.UWSub",
       "Fields.LoanTeamMember.Name.Underwriter",
       "Fields.LoanTeamMember.UserID.Underwriter",
       "Fields.1544",
       "Fields.1543",
       "Fields.2316",
       "Fields.2312",
       "Fields.1556",
       "Fields.VEND.X200"
     ],
     "sortOrder": [
       {
         "canonicalName": "Loan.LastModified",
         "order": "desc"
       }
     ],
     "includeArchivedLoans": false,
     "filter": {
       "operator": "and",
       "terms": [
         {
           "canonicalName": "Loan.LastModified",
           "value": "2023-01-21T14:38:49.708Z",
           "matchType": "greaterThanOrEquals",
           "precision": "exact"
         },
         {
           "operator": "or",
           "terms": [
             {
               "canonicalName": "Loan.LoanFolder",
               "value": "Adverse",
               "matchType": "exact",
               "include": true
             },
             {
               "canonicalName": "Loan.LoanFolder",
               "value": "Now in Underwriting",
               "matchType": "exact",
               "include": true
             },
             {
               "canonicalName": "Loan.LoanFolder",
               "value": "My Pipeline",
               "matchType": "exact",
               "include": true
             },
             {
               "canonicalName": "Loan.LoanFolder",
               "value": "Closed",
               "matchType": "exact",
               "include": true
             },
             {
               "canonicalName": "Loan.LoanFolder",
               "value": "Adverse Archive",
               "matchType": "exact",
               "include": true
             },
             {
               "canonicalName": "Loan.LoanFolder",
               "value": "TD Leads (not enough information)",
               "matchType": "exact",
               "include": true
             },
             {
               "canonicalName": "Loan.LoanFolder",
               "value": "Prospects",
               "matchType": "exact",
               "include": true
             }
           ]
         }
       ]
     }
   }