LET vSetupURL =  Pick(vUseDEVAPI + 1, 'https://api.coheus1.com/config/$(vXMLName)/fullxml', 'https://dev-api.coheus1.com/config/$(vXMLName)/fullxml');

TRACE vSetupURL: $(vSetupURL);

Set ErrorMode = 0;
ConfigurationData:
LOAD
    Concat("@1:n",'',RecNo()) as full_xml
FROM [lib://Web Setup XML V2 (azure_devang.ghela@3vuellc.com)]
(URL is [$(vSetupURL)],fix, codepage is 1252, no labels)
;

Set ErrorMode = 1;
Let vFileExists = if( NoOfRows('ConfigurationData') > 0, 1, 0);